name: CI
on: [push, pull_request]

jobs:

  package-haxelib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: away3d-haxelib
          path: |
            ./
            !scripts/
            !haxe-*-*/
            !neko-*-*/
            !.git/
          if-no-files-found: error

  unit-test-hashlink:
    # AL init fails on both windows and ubuntu
    # macos-14 is arm64, which setup-haxe doesn't support yet
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install utest --quiet

      - name: Setup environment
        run: |
          haxelib dev svg ${{ github.workspace }}

      - name: Run tests on HashLink
        working-directory: test
        run: |
          haxelib run openfl test hl
