name: CI
on: [push, pull_request]

jobs:

  package-haxelib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: away3d-haxelib
          path: |
            ./
            !scripts/
            !haxe-*-*/
            !neko-*-*/
            !.git/
          if-no-files-found: error
